apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  project: dev
  source:
    repoURL: https://github.com/yyyujini/eks-cicd.git
    targetRevision: HEAD
    path: app-of-apps
    helm:
      valueFiles:
        - values-local.yaml
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - PrunePropagationPolicy=background
